package com.ahong.PO;

public class TMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.MENU_ID
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.MENU_NAME
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.MENU_URL
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    private String menuUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.MENU_ID
     *
     * @return the value of t_menu.MENU_ID
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.MENU_ID
     *
     * @param menuId the value for t_menu.MENU_ID
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.MENU_NAME
     *
     * @return the value of t_menu.MENU_NAME
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.MENU_NAME
     *
     * @param menuName the value for t_menu.MENU_NAME
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.MENU_URL
     *
     * @return the value of t_menu.MENU_URL
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.MENU_URL
     *
     * @param menuUrl the value for t_menu.MENU_URL
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }
}