package com.ahong.PO;

public class TRoleMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_menu.ROLE_ID
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_menu.MENU_ID
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    private String menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_menu.ROLE_ID
     *
     * @return the value of t_role_menu.ROLE_ID
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_menu.ROLE_ID
     *
     * @param roleId the value for t_role_menu.ROLE_ID
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_menu.MENU_ID
     *
     * @return the value of t_role_menu.MENU_ID
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_menu.MENU_ID
     *
     * @param menuId the value for t_role_menu.MENU_ID
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }
}