package com.ahong.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ahong.PO.TMenu;
import com.ahong.PO.TMenuExample;

public interface TMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    long countByExample(TMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int deleteByExample(TMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int deleteByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int insert(TMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int insertSelective(TMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    List<TMenu> selectByExample(TMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    TMenu selectByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") TMenu record, @Param("example") TMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int updateByExample(@Param("record") TMenu record, @Param("example") TMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int updateByPrimaryKeySelective(TMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int updateByPrimaryKey(TMenu record);
}