package com.ahong.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ahong.PO.TRoleMenu;
import com.ahong.PO.TRoleMenuExample;

public interface TRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    long countByExample(TRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int deleteByExample(TRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int insert(TRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int insertSelective(TRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    List<TRoleMenu> selectByExample(TRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") TRoleMenu record, @Param("example") TRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int updateByExample(@Param("record") TRoleMenu record, @Param("example") TRoleMenuExample example);
}