package com.ahong.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ahong.PO.TUserRole;
import com.ahong.PO.TUserRoleExample;

public interface TUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    long countByExample(TUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int deleteByExample(TUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int insert(TUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int insertSelective(TUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    List<TUserRole> selectByExample(TUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") TUserRole record, @Param("example") TUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbg.generated Wed May 13 09:41:07 CST 2020
     */
    int updateByExample(@Param("record") TUserRole record, @Param("example") TUserRoleExample example);
}